services:
  - type: web
    name: tienda-online
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tienda-db
          property: connectionString
      - key: WHATSAPP_TOKEN
        value: tu_token_de_whatsapp
      - key: WHATSAPP_PHONE_ID
        value: tu_phone_id
      - key: WHATSAPP_RECIPIENT
        value: 51999999999

databases:
  - name: tienda-db
    plan: free
